### ISSUE TITLE
art exits with segmentation fault (sigsegv) while claiming to exit with signal 1 when xrootd fails on secondary input

### ISSUE THREAD

**Issue by knoepfel** [art-framework-suite/art#112]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/26250 (FNAL account required)*
*Originally created by @brownd1978 on 2021-09-09 16:04:26*

----

Mu2e observes that art exits with sigsegv when there is a problem accessing a secondary input stream file via xrootd.  While the xrootd problem has nothing to do with art, the erroneous return code makes it difficult to distinguish IO problems from program bugs.  One can reproduce the problem using the SimJob MDC2020k musing, running /mu2e/app/users/brownd/MDC2020j/debug2.fcl on the build01 machine.  Since the secondary input file is specified to be accessed via xrootd, and mu2ebuild01 doesn't have xrootd access, the execution fails as listed below.  However, while art claims to exit with status 1, the process actually exits with status sigsegv.  While the setup of running an xrootd job on mu2ebuild01 is artificial, we believe we are seeing the same effect in grid jobs when access to the 2ndary file via xrootd fails during the job (presumably due to a network issue).  The symptom is that some jobs return status sigsegv, but run to completion when resubmitted or run interactively.  We also searched for memory errors in the job as an alternate explanation for the irreproducible behavior but didn't see any.  Note that this job is running in multi-threaded mode, with 2 threads.  Note too this was observed running art v03_09_03, but that wasn't an option in the pulldown menu.

<pre>
> mu2e -c debug2.fcl --nevts 1
...
%MSG-s ArtException:  PostEndJob 09-Sep-2021 10:18:20 CDT ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- FileOpenError BEGIN
      ---- FatalRootError BEGIN
        Fatal Root Error: TNetXNGFile::Open
        [FATAL] Auth failed
        ROOT severity: 3000
      ---- FatalRootError END
      Unable to open specified secondary event stream file root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/mu2e/scratch/datasets/phy-sim/sim/mu2e/MuBeamCat/MDC2020k/art/87/c4/sim.mu2e.MuBeamCat.MDC2020k.001201_00000000.art.
      The above exception was thrown while processing module ResamplingMixer/beamResampler run: 1201 subRun: 349 event: 2
    ---- FileOpenError END
    Exception going through path earlyFlashPath
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- BADINPUT BEGIN
      Mu2eG4MT::endSubRun() Error: inconsistent simStage: 1 vs 0
      The above exception was thrown while processing module Mu2eG4MT/g4run run: 1201 subRun: 349
    ---- BADINPUT END
    Exception going through path flashPath
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
%MSG
Art has completed and will exit with status 1.
Segmentation fault
</pre>

###  To setup environment (additional information from Dave)

<pre>
$ ssh youraccount@mu2ebuild01
$ source /cvmfs/mu2e.opensciencegrid.org/setupmu2e_art.sh
$ setup mu2e
$ setup muse
$ muse setup SimJob MDC2020k
$ mu2e -c /mu2e/app/users/brownd/MDC2020j/debug2.fcl
</pre>

**Comment by goodenou** [comment]
This problem has now been resolved in the Mu2e Offline code. See PR #700 https://github.com/Mu2e/Offline/pull/700 for full details. At a very basic level, the problem was occurring because when there is a failure in the job before the G4MT code calls produce for the first time that causes the job to shutdown, the main thread, rather than the Master Run Manager thread, calls the destructor for all of the geometry objects. There is some instance data associated with each G4VPlacement object that is not accessible by the main thread, only by the Master Run Manager.

**Comment by knoepfel** [comment]
Thanks, @goodenou.  We will then close this issue.

**Comment by goodenou** [comment]
Great, thanks!
