### ISSUE TITLE
art version output missing major version

### ISSUE THREAD

**Issue by PetrilloAtWork** [art-framework-suite/art#117]
With `art` `v3_09_03`, `art --version` output is:
```
art .09.03
```

Something like `art 3.09.03` is expected.

(also, as a user I am not offered to change labels, so the suggestion about adding "high priority" label in the GitHub issue if needed is moot; this is definitely a low priority issue anyway).

**Comment by knoepfel** [comment]
Thanks for the report, @PetrilloAtWork. This change occurred during the move from `cetbuildtools` to `cetmodules`.  We will add a test to catch this error in the future.

This bug fix will be included in art 3.10.00.
