### ISSUE TITLE
Redmine art page does not point to GitHub

### ISSUE THREAD

**Issue by PetrilloAtWork** [art-framework-suite/art#120]
Redmine _art_ page, where the documentation still resides, should somehow point users (who likely have it bookmarked in their browser or brain) to GitHub for opening new issues. _I_ failed to find any pointer, and I can only assume that the average user will have the same problem.
I request the addition of proper Redmine documentation, suggesting all of the following:
1. in the project overview, a mention that the code and issue tracker are held here, while the documentation is still there
2. in the wiki, a mention on opening issues in GitHub
3. in Redmine issue tracker, a open issue whose subject suggests to go open new issues to GitHub.

**Comment by knoepfel** [comment]
We will improve the documentation regarding the migration.

**Comment by knoepfel** [comment]
@PetrilloAtWork, we have updated each of the Redmine project overview and wiki pages with a notice regarding the migration to GitHub.
