### ISSUE TITLE
psql readline

### ISSUE THREAD

**Issue by rlcee** [art-framework-suite/art#130]
Can psql be compiled with readline, so we can use the command line arrows? 
[doc ref](https://www.postgresql.org/docs/current/app-psql.html)

> mu2ebuild01 db > pg_config --configure
>  '--prefix=/scratch/workspace/canvas-products/label1/swarm/label2/SLF7/build/postgresql/v14_5/Linux64bit+3.10-2.17-p3913' '--with-gssapi' '--enable-thread-safety' '--with-perl' '--with-tcl' '--with-python' '--without-readline' 'PKG_CONFIG_PATH=/scratch/workspace/canvas-products/label1/swarm/label2/SLF7/build/python/v3_9_13/Linux64bit+3.10-2.17/lib/pkgconfig:/scratch/workspace/canvas-products/label1/swarm/label2/SLF7/build/sqlite/v3_39_02_00/Linux64bit+3.10-2.17/lib/pkgconfig:/scratch/workspace/canvas-products/label1/swarm/label2/SLF7/build/postgresql/v14_5/Linux64bit+3.10-2.17-p3913/lib/pkgconfig'
> mu2ebuild01 db > 
> mu2ebuild01 db > which psql
> /cvmfs/mu2e.opensciencegrid.org/artexternals/postgresql/v14_5/Linux64bit+3.10-2.17-p3913/bin/psql
>

**Comment by knoepfel** [comment]
@rlcee, the version of ROOT that is included with the art 3.13 distribution now depends on a postgresql version that was built with readline support.  Because readline is GPL licensed, we had to be careful to make sure that the readline usage was limited to the binary executable file.
