### ISSUE TITLE
Request a mu bundle using ROOT v6.28 

### ISSUE THREAD

**Issue by kutschke** [art-framework-suite/art#131]
**Describe your request or issue**
ROOT v6.28/00 has just been announced.  We understand that this contains features that will improve our REve based event display and we would like to start to use them.  

**If this is a high-priority issue**
This is NOT a high priority issue.   It's Ok to wait a little bit to see if there are patch releases to this ROOT version.   A time frame of a month or so from now is fast enough.  We will update the ticket if our priorities evolve.

**Comment by kutschke** [comment]
An update.  The new ROOT also contains improvements to ROOT/TMVA SOFIE (“System for Optimized Fast Inference code Emit”).  We are now using this and need the features in ROOT v6.28/00.  So we request a my bundle built with this root at your earliest convenience.

**Comment by knoepfel** [comment]
Understood, @kutschke.  We will discuss the timeline for the next release at our team meeting on 2/12.

**Comment by knoepfel** [comment]
The mu distribution for art 3.13 is on SciSoft: http://scisoft.fnal.gov/scisoft/bundles/mu/v3_13_01
