### ISSUE TITLE
Do not not set a handler for signal 38

### ISSUE THREAD

**Issue by marcpaterno** [art-framework-suite/art#139]
**What problem are you trying to solve?**

Intel's VTune uses signal 38 (by default), and requires that the application NOT use that signal.
While it is possible to tell VTune to use some other signal number between SIGRTMIN and SIGRTMAX, there must be one signal free for its use.
Currently art's UnixSignalHander's `disableRTSigs` function sets the action for all such signals in a way that makes VTune think they are all used.

**Describe your feature request**

Do not make any calls to fiddle with signal handling for one of the signals between SIGRTMIN and SIGRTMAX.
Since VTune by default uses signal 38, that might as well be the only art leaves unmolested.

This is high priority because to is a blocker for the use of VTune in profiling any art jobs.

**Comment by greenc-FNAL** [comment]
Fixed by https://github.com/art-framework-suite/art/commit/e595940024a7b346161ff944c51a3c2e69b12ced.
